### ISSUE TITLE
SelectPictureFragment: Deal with deprecation

### ISSUE THREAD

**Issue by martin-lenweiter** [HumanLearning2021/HumanLearningApp#133]
maybe add an issue

_Originally posted by @Nitwix in https://github.com/HumanLearning2021/HumanLearningApp/pull/118#discussion_r625805035_

**Comment by bbjubjub2494** [comment]
For context, using officially deprecated methods is currently recommended by the [official documentation,](https://developer.android.com/training/data-storage/shared/documents-files#open-file) so we don't really know if there's a way to solve this problem.
