### ISSUE TITLE
Make proper README with list of functionalities & install instructions (?)

### ISSUE THREAD

**Issue by bbjubjub2494** [HumanLearning2021/HumanLearningApp#223]

**Comment by Nitwix** [comment]
It is very important that we indicate the minimum version of android with which our app works, otherwise the assistants might get random crashes

**Comment by wattsecs** [comment]
> 
> 
> It is very important that we indicate the minimum version of android with which our app works, otherwise the assistants might get random crashes

I believe that this is not necessary because the relase will be in the form of an apk which will check on installation the API version of the device with the one required by the application
